blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page
from blog.apps import BlogConfig

from blog import views

app_name = BlogConfig.name

urlpatterns = [
    path("", cache_page(60 * 15)(views.ArticleListView.as_view()), name="list"),
    path("article/<int:pk>/", cache_page(60 * 15)(views.ArticleDetailView.as_view()), name="detail"),
    path("create/", views.ArticleCreateView.as_view(), name="create"),
    path("update/<int:pk>/", views.ArticleUpdateView.as_view(), name="update"),
    path("delete/<int:pk>/", views.ArticleDeleteView.as_view(), name="delete"),
]

config/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from config.settings import DEBUG
from debug_toolbar.toolbar import debug_toolbar_urls


urlpatterns = [
    path("ckeditor5/", include("django_ckeditor_5.urls")),
    path("admin/", admin.site.urls),
    path("", include("sender.urls", namespace="sender")),
    path("users/", include("users.urls", namespace="users")),
    path("blog/", include("blog.urls", namespace="blog")),
]

if DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += debug_toolbar_urls()

sender/urls.py
from django.urls import path

from sender import views
from sender.apps import SenderConfig

app_name = SenderConfig.name

urlpatterns = [
    path("", views.index, name="index"),

    path("clients/", views.ClientListView.as_view(), name="client_list"),
    path("clients/<int:pk>/", views.ClientDetailView.as_view(), name="client_detail"),
    path("clients/create/", views.ClientCreateView.as_view(), name="client_create"),
    path("clients/update/<int:pk>/", views.ClientUpdateView.as_view(), name="client_update"),
    path("clients/delete/<int:pk>/", views.ClientDeleteView.as_view(), name="client_delete"),

    path("texts/", views.TextListView.as_view(), name="text_list"),
    path("texts/<int:pk>/", views.TextDetailView.as_view(), name="text_detail"),
    path("texts/create/", views.TextCreateView.as_view(), name="text_create"),
    path("texts/update/<int:pk>/", views.TextUpdateView.as_view(), name="text_update"),
    path("texts/delete/<int:pk>/", views.TextDeleteView.as_view(), name="text_delete"),

    path("mailings/", views.MailingListView.as_view(), name="mailing_list"),
    path("mailings/<int:pk>/", views.MailingDetailView.as_view(), name="mailing_detail"),
    path("mailings/create/", views.MailingCreateView.as_view(), name="mailing_create"),
    path("mailings/update/<int:pk>/", views.MailingUpdateView.as_view(), name="mailing_update"),
    path("mailings/delete/<int:pk>/", views.MailingDeleteView.as_view(), name="mailing_delete"),
    path("mailings/disable/<int:pk>/", views.disable_mailing, name="disable_mailing"),

    path("attempt/clear/<int:pk>/", views.AttemptDeleteView.as_view(), name="attempt_clear"),    
]

users/urls.py
from django.urls import path

from django.contrib.auth.views import LogoutView

from users import views
from users.apps import UsersConfig

app_name = UsersConfig.name

urlpatterns = [
    path("register/", views.UserCreateView.as_view(), name="register"),
    path("confirm-email/<str:token>/", views.confirm_email, name="confirm_email"),
    path("info/", views.info_confirm_email, name="info"),
    path("login/", views.CustomLoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("profile/", views.ProfileView.as_view(), name="profile"),
    path("password-change/", views.CustomPasswordChangeView.as_view(), name="password_change"),
    path("password-change-done/", views.CustomPasswordChangeDoneView.as_view(), name="password_change_done"),
    path("password-reset/", views.CustomPasswordResetView.as_view(), name="password_reset"),
    path("password-reset-done/", views.CustomPasswordResetDoneView.as_view(), name="password_reset_done"),
    path("password-reset-confirm/<uidb64>/<token>/", views.CustomPasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    path("password-reset-complete/", views.CustomPasswordResetCompleteView.as_view(), name="password_reset_complete"),
    path("list/", views.UserListView.as_view(), name="user_list"),
    path("change-user-activity/<int:pk>", views.change_user_activity, name="change_user_activity"),
]

blog/models.py
from django.db import models

NULLABLE = {"blank": True, "null": True}

class Article(models.Model):
    title = models.CharField(verbose_name="Заголовок", max_length=150)
    slug = models.SlugField(verbose_name="slug", max_length=250, unique=True)
    content = models.TextField(verbose_name="Содержимое статьи", **NULLABLE)
    preview = models.ImageField(verbose_name="Превью", upload_to="blog/", **NULLABLE)
    views_count = models.IntegerField(verbose_name="Количество просмотров", default=0, editable=False)
    is_published = models.BooleanField(verbose_name="Опубликован", default=False)
    public_date = models.DateField(verbose_name="Дата публикации", auto_now=True)

    def __str__(self) -> str:
        return self.title

    class Meta:
        verbose_name = "статью"
        verbose_name_plural = "Статьи"
        ordering = ("-id",)

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

NULLABLE = {"blank": True, "null": True}


class User(AbstractUser):
    username = None
    email = models.EmailField(verbose_name="Почта", unique=True)
    token = models.CharField(max_length=16, **NULLABLE)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = "пользователя"
        verbose_name_plural = "пользователи"
        ordering = ("-pk",)
        permissions = {
            ("block_user", "Может блокировать пользователя"),
        }

templates/includes/main_menu.html
<header>
  <nav class="navbar navbar-expand-md fixed-top bg-primary" data-bs-theme="dark">
    <div class="container">
      <a class="navbar-brand" href="{% url 'sender:index' %}">SendEasy</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
      <div class="collapse navbar-collapse justify-content-between" id="navbarCollapse">
        <div>
          <ul class="navbar-nav me-auto mb-2 mb-md-0">            
            {% if user.is_authenticated %}
              {% if not perms.users.view_user and not perms.blog.add_article %}
              <li class="nav-item">
                <a class="nav-link {% if '/clients/' in request.path %}active{% endif %}" href="{% url 'sender:client_list' %}">Клиенты</a>
              </li>
              <li class="nav-item">
                <a class="nav-link {% if '/texts/' in request.path %}active{% endif %}" href="{% url 'sender:text_list' %}">Письма</a>
              </li>
              {% endif %}
            {% if not  perms.blog.add_article %}
            <li class="nav-item">
              <a class="nav-link {% if '/mailings/' in request.path %}active{% endif %}" href="{% url 'sender:mailing_list' %}">Рассылки</a>
            </li>
            {% endif %}
            {% endif %}
            {% if perms.users.view_user or user.is_superuser %}
            <li class="nav-item">
              <a class="nav-link {% if '/users/' in request.path %}active{% endif %}" href="{% url 'users:user_list' %}">Пользователи сервиса</a>
            </li>
            {% endif %}
            {% if perms.blog.change_article or user.is_superuser %}
            <li class="nav-item">
              <a class="nav-link {% if '/blog/' in request.path %}active{% endif %}" href="{% url 'blog:list' %}">Блог</a>
            </li>
            {% endif %}
          </ul>
        </div>
        <div>
          <ul class="navbar-nav me-auto mb-2 mb-md-0">
            {% if not user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link {% if '/users/login/' in request.path %}active{% endif %}" href="{% url 'users:login' %}">Вход</a>
              </li>
              <li class="nav-item">
                <a class="nav-link {% if '/users/register/' in request.path %}active{% endif %}" href="{% url 'users:register' %}">Регистрация</a>
              </li>
            {% else %}
              <li class="nav-item">
                <a class="nav-link {% if '/users/profile/' in request.path %}active{% endif %}" href="{% url 'users:profile' %}">Профиль</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'users:logout' %}">Выход</a>
              </li>
            {% endif %}
          </ul>
        </div>
      </div>
    </div>
  </nav>
</header>

templates/includes/theme_button.html
<svg xmlns="http://www.w3.org/2000/svg" class="d-none">
  <symbol id="check2" viewBox="0 0 16 16">
    <path d="M13.854 3.646a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708 0l-3.5-3.5a.5.5 0 1 1 .708-.708L6.5 10.293l6.646-6.647a.5.5 0 0 1 .708 0z" />
  </symbol>
  <symbol id="circle-half" viewBox="0 0 16 16">
    <path d="M8 15A7 7 0 1 0 8 1v14zm0 1A8 8 0 1 1 8 0a8 8 0 0 1 0 16z" />
  </symbol>
  <symbol id="moon-stars-fill" viewBox="0 0 16 16">
    <path d="M6 .278a.768.768 0 0 1 .08.858 7.208 7.208 0 0 0-.878 3.46c0 4.021 3.278 7.277 7.318 7.277.527 0 1.04-.055 1.533-.16a.787.787 0 0 1 .81.316.733.733 0 0 1-.031.893A8.349 8.349 0 0 1 8.344 16C3.734 16 0 12.286 0 7.71 0 4.266 2.114 1.312 5.124.06A.752.752 0 0 1 6 .278z" />
    <path d="M10.794 3.148a.217.217 0 0 1 .412 0l.387 1.162c.173.518.579.924 1.097 1.097l1.162.387a.217.217 0 0 1 0 .412l-1.162.387a1.734 1.734 0 0 0-1.097 1.097l-.387 1.162a.217.217 0 0 1-.412 0l-.387-1.162A1.734 1.734 0 0 0 9.31 6.593l-1.162-.387a.217.217 0 0 1 0-.412l1.162-.387a1.734 1.734 0 0 0 1.097-1.097l.387-1.162zM13.863.099a.145.145 0 0 1 .274 0l.258.774c.115.346.386.617.732.732l.774.258a.145.145 0 0 1 0 .274l-.774.258a1.156 1.156 0 0 0-.732.732l-.258.774a.145.145 0 0 1-.274 0l-.258-.774a1.156 1.156 0 0 0-.732-.732l-.774-.258a.145.145 0 0 1 0-.274l.774-.258c.346-.115.617-.386.732-.732L13.863.1z" />
  </symbol>
  <symbol id="sun-fill" viewBox="0 0 16 16">
    <path d="M8 12a4 4 0 1 0 0-8 4 4 0 0 0 0 8zM8 0a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 0zm0 13a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 13zm8-5a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2a.5.5 0 0 1 .5.5zM3 8a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2A.5.5 0 0 1 3 8zm10.657-5.657a.5.5 0 0 1 0 .707l-1.414 1.415a.5.5 0 1 1-.707-.708l1.414-1.414a.5.5 0 0 1 .707 0zm-9.193 9.193a.5.5 0 0 1 0 .707L3.05 13.657a.5.5 0 0 1-.707-.707l1.414-1.414a.5.5 0 0 1 .707 0zm9.193 2.121a.5.5 0 0 1-.707 0l-1.414-1.414a.5.5 0 0 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .707zM4.464 4.465a.5.5 0 0 1-.707 0L2.343 3.05a.5.5 0 1 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .708z" />
  </symbol>
</svg>

<div class="dropdown position-fixed bottom-0 end-0 mb-3 me-3 bd-mode-toggle">
  <button class="btn btn-bd-primary py-2 dropdown-toggle d-flex align-items-center" id="bd-theme" type="button" aria-expanded="false" data-bs-toggle="dropdown" aria-label="Toggle theme (auto)">
    <svg class="bi my-1 theme-icon-active" width="1em" height="1em">
      <use href="#circle-half"></use>
    </svg>
    <span class="visually-hidden" id="bd-theme-text">SendEasy</span>
  </button>
  <ul class="dropdown-menu dropdown-menu-end shadow" aria-labelledby="bd-theme-text">
    <li>
      <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="light" aria-pressed="false">
        <svg class="bi me-2 opacity-50" width="1em" height="1em">
          <use href="#sun-fill"></use>
        </svg>Light<svg class="bi ms-auto d-none" width="1em" height="1em">
          <use href="#check2"></use>
        </svg>
      </button>
    </li>
    <li>
      <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="dark" aria-pressed="false">
        <svg class="bi me-2 opacity-50" width="1em" height="1em">
          <use href="#moon-stars-fill"></use>
        </svg>Dark<svg class="bi ms-auto d-none" width="1em" height="1em">
          <use href="#check2"></use>
        </svg>
      </button>
    </li>
    <li>
      <button type="button" class="dropdown-item d-flex align-items-center active" data-bs-theme-value="auto" aria-pressed="true">
        <svg class="bi me-2 opacity-50" width="1em" height="1em">
          <use href="#circle-half"></use>
        </svg>Auto<svg class="bi ms-auto d-none" width="1em" height="1em">
          <use href="#check2"></use>
        </svg>
      </button>
    </li>
  </ul>
</div>