blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page
from blog.apps import BlogConfig

from blog import views

app_name = BlogConfig.name

urlpatterns = [
    path("", cache_page(60 * 15)(views.ArticleListView.as_view()), name="list"),
    path("article/<int:pk>/", cache_page(60 * 15)(views.ArticleDetailView.as_view()), name="detail"),
    path("create/", views.ArticleCreateView.as_view(), name="create"),
    path("update/<int:pk>/", views.ArticleUpdateView.as_view(), name="update"),
    path("delete/<int:pk>/", views.ArticleDeleteView.as_view(), name="delete"),
]

config/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from config.settings import DEBUG
from debug_toolbar.toolbar import debug_toolbar_urls


urlpatterns = [
    path("ckeditor5/", include("django_ckeditor_5.urls")),
    path("admin/", admin.site.urls),
    path("", include("sender.urls", namespace="sender")),
    path("users/", include("users.urls", namespace="users")),
    path("blog/", include("blog.urls", namespace="blog")),
]

if DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += debug_toolbar_urls()

sender/urls.py
from django.urls import path

from sender import views
from sender.apps import SenderConfig

app_name = SenderConfig.name

urlpatterns = [
    path("", views.index, name="index"),

    path("clients/", views.ClientListView.as_view(), name="client_list"),
    path("clients/<int:pk>/", views.ClientDetailView.as_view(), name="client_detail"),
    path("clients/create/", views.ClientCreateView.as_view(), name="client_create"),
    path("clients/update/<int:pk>/", views.ClientUpdateView.as_view(), name="client_update"),
    path("clients/delete/<int:pk>/", views.ClientDeleteView.as_view(), name="client_delete"),

    path("texts/", views.TextListView.as_view(), name="text_list"),
    path("texts/<int:pk>/", views.TextDetailView.as_view(), name="text_detail"),
    path("texts/create/", views.TextCreateView.as_view(), name="text_create"),
    path("texts/update/<int:pk>/", views.TextUpdateView.as_view(), name="text_update"),
    path("texts/delete/<int:pk>/", views.TextDeleteView.as_view(), name="text_delete"),

    path("mailings/", views.MailingListView.as_view(), name="mailing_list"),
    path("mailings/<int:pk>/", views.MailingDetailView.as_view(), name="mailing_detail"),
    path("mailings/create/", views.MailingCreateView.as_view(), name="mailing_create"),
    path("mailings/update/<int:pk>/", views.MailingUpdateView.as_view(), name="mailing_update"),
    path("mailings/delete/<int:pk>/", views.MailingDeleteView.as_view(), name="mailing_delete"),
    path("mailings/disable/<int:pk>/", views.disable_mailing, name="disable_mailing"),

    path("attempt/clear/<int:pk>/", views.AttemptDeleteView.as_view(), name="attempt_clear"),    
]

blog/models.py
from django.db import models

NULLABLE = {"blank": True, "null": True}

class Article(models.Model):
    title = models.CharField(verbose_name="Заголовок", max_length=150)
    slug = models.SlugField(verbose_name="slug", max_length=250, unique=True)
    content = models.TextField(verbose_name="Содержимое статьи", **NULLABLE)
    preview = models.ImageField(verbose_name="Превью", upload_to="blog/", **NULLABLE)
    views_count = models.IntegerField(verbose_name="Количество просмотров", default=0, editable=False)
    is_published = models.BooleanField(verbose_name="Опубликован", default=False)
    public_date = models.DateField(verbose_name="Дата публикации", auto_now=True)

    def __str__(self) -> str:
        return self.title

    class Meta:
        verbose_name = "статью"
        verbose_name_plural = "Статьи"
        ordering = ("-id",)

blog/forms.py
from django import forms

from blog.models import Article
from sender.forms import FormStyleMixin


class ArticleModelForm(FormStyleMixin, forms.ModelForm):

    class Meta:
        model = Article
        fields = (
            "title",
            "preview",
            "content",
            "is_published",
        )

blog/views.py
from datetime import datetime

from django.contrib.auth.mixins import PermissionRequiredMixin
from django.urls import reverse, reverse_lazy
from django.views.generic import (
    CreateView,
    DeleteView,
    DetailView,
    ListView,
    UpdateView,
)

from blog.forms import ArticleModelForm
from blog.models import Article
from blog.utils import generate_slug


class ArticleListView(PermissionRequiredMixin, ListView):
    """Список статей"""

    model = Article
    paginate_by = 5
    extra_context = {"title": "Блог"}
    permission_required = "blog.change_article"


class ArticleDetailView(DetailView):
    """Просмотр статьи"""

    model = Article

    def get_object(self, queryset=None):
        obj = super().get_object()
        obj.views_count += 1
        obj.save(update_fields=["views_count"])

        return obj


class ArticleCreateView(PermissionRequiredMixin, CreateView):
    """Создание статьи"""

    model = Article
    form_class = ArticleModelForm
    success_url = reverse_lazy("blog:list")
    extra_context = {"title": "Добавление статьи"}
    permission_required = "blog.add_article"

    def form_valid(self, form):
        if form.is_valid():
            new_article = form.save()

            # Генерация слага
            new_article.slug = generate_slug(Article, new_article.title)

            # Назначение владельца
            new_article.owner = self.request.user

            # Заполнение даты публикации при нажатии соответствующего флага
            if new_article.is_published:
                new_article.public_date = datetime.now()
            else:
                new_article.public_date = None

            new_article.save()

        return super().form_valid(form)


class ArticleUpdateView(PermissionRequiredMixin, UpdateView):
    """Редактирование статьи"""

    model = Article
    form_class = ArticleModelForm
    permission_required = "blog.change_article"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Изменение статьи"
        return context

    def form_valid(self, form):
        if form.is_valid():
            old_article = form.save()

            if old_article.is_published:
                old_article.public_date = datetime.now()
            else:
                old_article.public_date = None

            old_article.save()

        return super().form_valid(form)

    def get_success_url(self):
        return reverse("blog:detail", args=[self.kwargs.get("pk")])


class ArticleDeleteView(PermissionRequiredMixin, DeleteView):
    """Удаление статьи"""

    model = Article
    success_url = reverse_lazy("blog:list")
    permission_required = "blog.delete_article"

blog/templates/blog/article_confirm_delete.html
{% extends 'base.html' %}
{% load static %}
{% load my_tags %}

{% block content %}
  <div class="container">

    <div class="row mt-4">
        <div class="col-12">
            <h2 class="display-5">Удалить статью "{{ object.title }}"?</h2>
            <form method="post">
              {% csrf_token %}
              <button type="submit" class="btn btn-danger">Ок</button>
              <a class="btn btn-primary" href="{% url "blog:list" %}">Отмена</a>
            </form>
        </div>
    </div>
  </div>
{% endblock %}

blog/templates/blog/article_detail.html
{% extends 'base.html' %}
{% load static %}
{% load my_tags %}

{% block content %}
<h1 class="card-title text-center">{{ object.title|capfirst }}</h1>
  <div class="card mt-4">
    <div class="card-header d-flex justify-content-between align-items-center">
      <div></div>
      <div>
        <a href="{% url 'sender:index' %}" class="btn btn-primary">Назад</a>
        {% if object.owner == user or perms.blog.change_article %}
          <a href="{% url 'blog:update' object.pk %}" class="btn btn-primary">Редактировать</a>
        {% endif %}
        {% if perms.blog.delete_article or user.is_superuser %}
          <a href="{% url 'blog:delete' object.pk %}" class="btn btn-outline-danger">Удалить</a>
        {% endif %}
      </div>
    </div>
    <div class="card-body">
      {% if object.preview %}
        <img src="{{ object.preview|media_filter }}" class="card-img-top" alt="{{ object.title }}" />
      {% endif %}
      <p class="lead">{{ object.content|linebreaksbr }}</p>
      <p class="lead">Дата публикации: {{ object.public_date }}</p>
      <p class="lead">Просмотров: {{ object.views_count }}</p>
    </div>
  </div>
{% endblock %}

blog/templates/blog/article_form.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  <div class="row justify-content-center">
    <div class="col">
      <h1 class="m-5 text-center">{{ title }}</h1>
      <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{form.as_p}}

        <div class="row-cols-2">
          <div class="d-flex gap-3">
            <button type="submit" class="btn btn-primary form-control">{% if object %}Сохранить{% else %}Создать{% endif %}</button>
            <a class="btn btn-secondary form-control"
            href="
              {% if object %}
                {% url "blog:detail" object.pk %}
              {% else %}
                {% url "blog:list" %}
              {% endif %}
            ">Отмена</a>
          </div>        
        </div>        
      </form>
    </div>
  </div>
{% endblock %}

blog/templates/blog/article_list.html
{% extends 'base.html' %}
{% load static %}
{% load my_tags %}

{% block content %}
  <div class="row mt-5">
    <h1>{{ title }}</h1>
  </div>
  <div class="m-2">
    <a class="btn btn-primary" href="{% url 'blog:create' %}">Добавить статью</a>
  </div>

  <div class="row mb-2">
    {% for object in page_obj %}
      <div class="col-md-12">
        <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
          <div class="col p-4 d-flex flex-column position-static">
            <h3 class="mb-0">{{ object.title }}</h3>
            {% if object.is_published %}
              <div class="mb-1 text-body-secondary">{{ object.public_date }}</div>
            {% else %}
              <div class="mb-1 text-bg-warning">Не опубликовано</div>
            {% endif %}                
            <p class="card-text mb-auto">{{ object.content|truncatechars:300 }}</p>
            <div class="mb-1 text-body-secondary">Просмотров: {{ object.views_count }}</div>
            <a href="{% url 'blog:detail' object.pk %}" class="icon-link gap-1 icon-link-hover stretched-link">Продолжить чтение</a>
          </div>
          <div class="col-auto d-none d-lg-block">
            {% if object.preview %}
              <img height="250" src="{{ object.preview|media_filter }}" class="card-img-top" alt="{{ object.title }}" />
            {% endif %}
          </div>
        </div>
      </div>
    {% endfor %}
  </div>

  {% if page_obj %}
  <nav>
    <ul class="pagination">
      <li class="page-item {% if not page_obj.has_previous %}disabled{% endif %}">
        <a class="page-link" href="{% if page_obj.has_previous %}
        {% url 'sender:client_list' %}?page={{ page_obj.previous_page_number }}{% endif %}">
        Назад</a>
      </li>

      {% for page in page_obj.paginator.page_range %}
        {% if page <= page_obj.number|add:2 and page >= page_obj.number|add:-2 %}
          <li class="page-item {% if page == page_obj.number %}active{% endif %}">
            <a class="page-link" href="{% url 'sender:client_list' %}?page={{ page }}">{{ page }}</a>
          </li>
        {% endif %}
      {% endfor %}

      <li class="page-item {% if not page_obj.has_next %}disabled{% endif %}">
        <a class="page-link" href="
        {% if page_obj.has_next %}{% url 'sender:client_list' %}?page={{ page_obj.next_page_number }}{% endif %}">
        Вперед</a>
      </li>
    </ul>
  </nav>
  {% endif %}
{% endblock %}