blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page
from blog.apps import BlogConfig

from blog import views

app_name = BlogConfig.name

urlpatterns = [
    path("", cache_page(60 * 15)(views.ArticleListView.as_view()), name="list"),
    path("article/<int:pk>/", cache_page(60 * 15)(views.ArticleDetailView.as_view()), name="detail"),
    path("create/", views.ArticleCreateView.as_view(), name="create"),
    path("update/<int:pk>/", views.ArticleUpdateView.as_view(), name="update"),
    path("delete/<int:pk>/", views.ArticleDeleteView.as_view(), name="delete"),
]

config/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from config.settings import DEBUG
from debug_toolbar.toolbar import debug_toolbar_urls


urlpatterns = [
    path("ckeditor5/", include("django_ckeditor_5.urls")),
    path("admin/", admin.site.urls),
    path("", include("sender.urls", namespace="sender")),
    path("users/", include("users.urls", namespace="users")),
    path("blog/", include("blog.urls", namespace="blog")),
]

if DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += debug_toolbar_urls()

sender/urls.py
from django.urls import path

from sender import views
from sender.apps import SenderConfig

app_name = SenderConfig.name

urlpatterns = [
    path("", views.index, name="index"),

    path("clients/", views.ClientListView.as_view(), name="client_list"),
    path("clients/<int:pk>/", views.ClientDetailView.as_view(), name="client_detail"),
    path("clients/create/", views.ClientCreateView.as_view(), name="client_create"),
    path("clients/update/<int:pk>/", views.ClientUpdateView.as_view(), name="client_update"),
    path("clients/delete/<int:pk>/", views.ClientDeleteView.as_view(), name="client_delete"),

    path("texts/", views.TextListView.as_view(), name="text_list"),
    path("texts/<int:pk>/", views.TextDetailView.as_view(), name="text_detail"),
    path("texts/create/", views.TextCreateView.as_view(), name="text_create"),
    path("texts/update/<int:pk>/", views.TextUpdateView.as_view(), name="text_update"),
    path("texts/delete/<int:pk>/", views.TextDeleteView.as_view(), name="text_delete"),

    path("mailings/", views.MailingListView.as_view(), name="mailing_list"),
    path("mailings/<int:pk>/", views.MailingDetailView.as_view(), name="mailing_detail"),
    path("mailings/create/", views.MailingCreateView.as_view(), name="mailing_create"),
    path("mailings/update/<int:pk>/", views.MailingUpdateView.as_view(), name="mailing_update"),
    path("mailings/delete/<int:pk>/", views.MailingDeleteView.as_view(), name="mailing_delete"),
    path("mailings/disable/<int:pk>/", views.disable_mailing, name="disable_mailing"),

    path("attempt/clear/<int:pk>/", views.AttemptDeleteView.as_view(), name="attempt_clear"),    
]

sender/models.py
from django_ckeditor_5.fields import CKEditor5Field
from django.db import models

from users.models import User


NULLABLE = {"blank": True, "null": True}


class Client(models.Model):
    name = models.CharField(verbose_name="Ф.И.О", max_length=150)
    email = models.EmailField(verbose_name="Email", max_length=150)
    comment = models.TextField(verbose_name="Комментарий", **NULLABLE)
    owner = models.ForeignKey(to=User, related_name="clients", verbose_name="Владелец", on_delete=models.CASCADE, **NULLABLE)

    def __str__(self):
        return f"{self.email} ({self.name})"

    class Meta:
        verbose_name = "клиента"
        verbose_name_plural = "клиенты"
        ordering = ("pk",)


class Text(models.Model):
    title = models.CharField(verbose_name="Тема", max_length=150)
    body = CKEditor5Field(verbose_name="Сообщение", **NULLABLE)
    owner = models.ForeignKey(to=User, related_name="texts", verbose_name="Владелец", on_delete=models.CASCADE, **NULLABLE)

    def __str__(self):
        return f"{self.title}"

    class Meta:
        verbose_name = "сообщение"
        verbose_name_plural = "сообщения"
        ordering = ("pk",)


class Mailing(models.Model):
    ONE_TIME = "O"
    DAY = "D"
    WEEK = "W"
    MONTH = "M"
    LAUNCH_FREQUENCY = [
        (ONE_TIME, "Одноразовая"),
        (DAY, "Раз в день"),
        (WEEK, "Раз в неделю"),
        (MONTH, "Раз в месяц"),
    ]

    CREATED = "C"
    RUNING = "R"
    STOPPED = "S"
    MAILING_STATUS = [
        (CREATED, "Создана"),
        (RUNING, "Запущена"),
        (STOPPED, "Завершена"),
    ]


    name = models.CharField(verbose_name="Наименование", max_length=150, **NULLABLE)
    start_datetime = models.DateTimeField(verbose_name="Время и дата старта")
    end_datetime = models.DateTimeField(verbose_name="Время и дата окончания", **NULLABLE)
    periodicity = models.CharField(verbose_name="Периодичность", max_length=1, choices=LAUNCH_FREQUENCY, default=ONE_TIME)
    status = models.CharField(verbose_name="Статус", max_length=1, choices=MAILING_STATUS, default=CREATED)
    clients = models.ManyToManyField(to=Client, verbose_name="Клиенты")
    text = models.ForeignKey(to=Text, verbose_name="Сообщение", on_delete=models.CASCADE, related_name="mailings")
    owner = models.ForeignKey(to=User, related_name="mailings", verbose_name="Владелец", on_delete=models.CASCADE, **NULLABLE)

    def __str__(self):
        return f"{self.name}"

    class Meta:
        verbose_name = "рассылку"
        verbose_name_plural = "рассылки"
        ordering = ("pk",)
        permissions = {
            ("disable_mailing", "Может отключать рассылку"),
        }


class Attempt(models.Model):
    mailing = models.ForeignKey(to=Mailing, verbose_name="Рассылка", related_name="attempts", on_delete=models.CASCADE, editable=False)
    started = models.DateTimeField(verbose_name="Дата и время запуска", auto_now=True, editable=False)
    status = models.BooleanField(verbose_name="Статус", default=True, editable=False)
    response_code = models.SmallIntegerField(verbose_name="Код ответа", editable=False)
    response_msg = models.CharField(verbose_name="Текст ответа сервера", max_length=250, editable=False, **NULLABLE)

    def __str__(self):
        return f"{self.started} | {self.mailing} | {self.status}"

    class Meta:
        verbose_name = "попытку"
        verbose_name_plural = "попытки"
        ordering = ("-started",)

sender/forms.py
from django import forms
from django_ckeditor_5.widgets import CKEditor5Widget
from sender.models import Client, Mailing, Text


class FormStyleMixin:
    """Стили для форм"""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field_name, field in self.fields.items():
            # Скрываем поле owner
            if field_name == "owner":
                field.widget = forms.HiddenInput()
                # field.required = False
                continue
            if isinstance(field, forms.fields.BooleanField):
                field.widget.attrs.update({"class": "form-check"})
                continue
            field.widget.attrs.update({"class": "form-control"})


class ClientModelForm(FormStyleMixin, forms.ModelForm):
    """Форма клиента"""

    class Meta:
        model = Client
        fields = "__all__"


class TextModelForm(FormStyleMixin, forms.ModelForm):
    """Форма сообщения"""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["body"].widget = CKEditor5Widget()

    class Meta:
        model = Text
        fields = "__all__"


class CustomDateTimeInput(forms.DateTimeInput):
    input_type = "datetime-local"


class MailingModelForm(FormStyleMixin, forms.ModelForm):
    """Форма рассылки"""

    start_datetime = forms.DateTimeField(
        widget=CustomDateTimeInput(format="%Y-%m-%dT%H:%M"),
        label="Время и дата старта",
    )
    end_datetime = forms.DateTimeField(
        widget=CustomDateTimeInput(format="%Y-%m-%dT%H:%M"),
        label="Время и дата окончания",
        required=False,
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["clients"].queryset = kwargs["initial"]["clients_queryset"]
        self.fields["text"].queryset = kwargs["initial"]["texts_queryset"]

    class Meta:
        model = Mailing
        fields = "__all__"

sender/views.py
from django.contrib.auth.decorators import permission_required
from django.contrib.auth.mixins import (
    LoginRequiredMixin,
    UserPassesTestMixin,
)
from django.core.exceptions import PermissionDenied
from django.forms import ValidationError
from django.shortcuts import redirect, render
from django.urls import reverse, reverse_lazy
from django.views import View
from django.views.generic import (
    CreateView,
    DeleteView,
    DetailView,
    ListView,
    UpdateView,
)

from blog.models import Article
from sender.forms import ClientModelForm, MailingModelForm, TextModelForm
from sender.models import Attempt, Client, Text, Mailing
from sender.services import get_statistic_from_cache


def index(request):
    """Главная страница"""

    statistic = get_statistic_from_cache()
    articles = Article.objects.order_by("?")[:3]

    context = {
        "mailings_count": statistic.get("mailings_count"),
        "mailings_count_active": statistic.get("mailings_active_count"),
        "clients_count": statistic.get("clients_count"),
        "articles": articles,
    }

    return render(request, "sender/index.html", context)


class ViewAccessMixin:
    """
    Показывает всё тем, у кого есть соответствующее разрешение,
    и скрывает от рядового пользователя чужое
    """

    def get_queryset(self):
        if self.request.user.has_perm(getattr(self, "permission_required", None)):
            return self.model.objects.all()
        return self.model.objects.filter(owner=self.request.user)


class ActionUserPassesTestMixin(UserPassesTestMixin):
    """Разрешает действия только владельцу или суперпользователю"""

    def test_func(self):
        user = self.request.user
        obj = self.get_object()
        return obj.owner == user or user.is_superuser


class ModeratorPassesTestMixin(UserPassesTestMixin):
    """Запрещает просмотр модераторам"""

    def test_func(self):
        return not self.request.user.is_staff


class CreatePermissionMixin:
    """Разрешает создавать объект всем, кроме модератора"""

    def get_form_class(self):
        if self.request.user.has_perms(
            [
                "users.block_user",
                "sender.disable_mailing",
            ]
        ):
            raise PermissionDenied
        return self.form_class


class ClientListView(
    LoginRequiredMixin, ViewAccessMixin, ModeratorPassesTestMixin, ListView
):
    """
    Список клиентов
    permission_required не назначен: список видят только владельцы
    Доступ к списку модератору запрещен
    """

    model = Client
    paginate_by = 50


class ClientDetailView(LoginRequiredMixin, ViewAccessMixin, DetailView):
    """Просмотр клиента"""

    model = Client
    permission_required = "sender.view_client"


class ClientCreateView(LoginRequiredMixin, CreatePermissionMixin, CreateView):
    """Добавление клиента"""

    model = Client
    form_class = ClientModelForm
    success_url = reverse_lazy("sender:client_list")

    def form_valid(self, form):
        user = self.request.user
        if form.is_valid:
            obj = form.save(commit=False)
            if Client.objects.filter(owner=user).filter(email=obj.email).exists():
                form.add_error("email", ValidationError("Клиент с такой почтой у Вас уже есть"))
                return self.form_invalid(form)
            obj.owner = user
            obj.save()

        return super().form_valid(form)


class ClientUpdateView(LoginRequiredMixin, ActionUserPassesTestMixin, UpdateView):
    """Редактирование клиента"""

    model = Client
    form_class = ClientModelForm

    def get_success_url(self):
        return reverse("sender:client_detail", args=[self.kwargs.get("pk")])


class ClientDeleteView(LoginRequiredMixin, ActionUserPassesTestMixin, DeleteView):
    """Удаление клиента"""

    model = Client
    success_url = reverse_lazy("sender:client_list")


class TextListView(
    LoginRequiredMixin, ViewAccessMixin, ModeratorPassesTestMixin, ListView
):
    """
    Список сообщений
    permission_required не назначен: список видят только владельцы
    Доступ к списку модератору запрещен
    """

    model = Text
    paginate_by = 50


class TextDetailView(LoginRequiredMixin, ViewAccessMixin, DetailView):
    """Просмотр сообщения"""

    model = Text
    permission_required = "sender.view_text"


class TextCreateView(LoginRequiredMixin, CreatePermissionMixin, CreateView):
    """Создание сообщения"""

    model = Text
    form_class = TextModelForm
    success_url = reverse_lazy("sender:text_list")

    def form_valid(self, form):
        if form.is_valid:
            obj = form.save()
            obj.owner = self.request.user

        return super().form_valid(form)


class TextUpdateView(LoginRequiredMixin, ActionUserPassesTestMixin, UpdateView):
    """Редактирование сообщения"""

    model = Text
    form_class = TextModelForm

    def get_success_url(self):
        return reverse("sender:text_detail", args=[self.kwargs.get("pk")])


class TextDeleteView(LoginRequiredMixin, ActionUserPassesTestMixin, DeleteView):
    """Удаление сообщения"""

    model = Text
    success_url = reverse_lazy("sender:text_list")


class MailingListView(LoginRequiredMixin, ViewAccessMixin, ListView):
    """Список рассылок"""

    model = Mailing
    paginate_by = 50
    permission_required = "sender.view_mailing"


class MailingDetailView(LoginRequiredMixin, ViewAccessMixin, DetailView):
    """Просмотр рассылки"""

    model = Mailing
    permission_required = "sender.view_mailing"

    def get_queryset(self):
        return super().get_queryset().select_related("text").prefetch_related("clients")

    def post(self, request, *args, **kwargs):
        """Изменение рассылки при onchange"""
        mailing = Mailing.objects.get(pk=kwargs.get("pk"))
        mailing.status = self.request.POST.get("status")
        mailing.periodicity = self.request.POST.get("periodicity")
        if mailing.periodicity == Mailing.ONE_TIME:
            mailing.end_datetime = None
            attempts = Attempt.objects.filter(mailing=mailing)
            for attempt in attempts:
                attempt.delete()
        mailing.save(update_fields=["status", "periodicity", "end_datetime"])

        return redirect("sender:mailing_detail", kwargs.get("pk"))


class MailingValidMixin:
    def form_valid(self, form):
        if form.is_valid():
            new_mailing = form.save(commit=False)
            # Если это не одноразовая рассылка, сверяем даты.
            if new_mailing.periodicity != Mailing.ONE_TIME:
                if new_mailing.start_datetime > new_mailing.end_datetime:
                    form.add_error(
                        "start_datetime",
                        "Дата старта не может быть позже даты окончания",
                    )
                    return self.form_invalid(form)
            else:
                # Если это одноразовая рассылка,
                # чистим дату окончания и все попытки, если были
                new_mailing.end_datetime = None
                attempts = Attempt.objects.filter(mailing=new_mailing)
                if attempts:
                    for attempt in attempts:
                        attempt.delete()
            new_mailing.save()

        return super().form_valid(form)


class MailingCreateView(
    LoginRequiredMixin, CreatePermissionMixin, MailingValidMixin, CreateView
):
    """Создание рассылки"""

    model = Mailing
    form_class = MailingModelForm
    success_url = reverse_lazy("sender:mailing_list")
   
    def get_initial(self):
        initial = super().get_initial()
        initial["clients_queryset"] = Client.objects.filter(owner=self.request.user)
        initial["texts_queryset"] = Text.objects.filter(owner=self.request.user)
        return initial


class MailingUpdateView(
    LoginRequiredMixin, ActionUserPassesTestMixin, MailingValidMixin, UpdateView
):
    """Редактирование рассылки"""

    model = Mailing
    form_class = MailingModelForm

    def get_success_url(self):
        return reverse("sender:mailing_detail", args=[self.kwargs.get("pk")])
    
    def get_initial(self):
        initial = super().get_initial()
        initial["clients_queryset"] = Client.objects.filter(owner=self.request.user)
        initial["texts_queryset"] = Text.objects.filter(owner=self.request.user)
        return initial


class MailingDeleteView(LoginRequiredMixin, ActionUserPassesTestMixin, DeleteView):
    """Удаление рассылки"""

    model = Mailing
    success_url = reverse_lazy("sender:mailing_list")


@permission_required("sender.disable_mailing", PermissionDenied)
def disable_mailing(request, pk):
    """Отключение рассылки может осуществлять только модератор"""

    mailing = Mailing.objects.get(pk=pk)
    if mailing.status != mailing.STOPPED:
        mailing.status = mailing.STOPPED
        mailing.save(update_fields=["status"])

    return redirect(reverse("sender:mailing_detail", args=[mailing.pk]))


class AttemptDeleteView(LoginRequiredMixin, ActionUserPassesTestMixin, View):
    """Удаление логов конкретной рассылки"""

    def post(self, request, *args, **kwargs):
        attempts = Attempt.objects.filter(mailing=kwargs.get("pk"))
        for attempt in attempts:
            attempt.delete()
        return redirect("sender:mailing_detail", kwargs.get("pk"))

sender/templates/sender/client_detail.html
{% extends 'base.html' %}

{% block content %}
  <h1 class="mt-5">Информация о клиенте</h1>
  <div class="card mt-4">
    <div class="card-header d-flex justify-content-between align-items-center">
      <div>
        <h5 class="card-title">{{ object.name }}</h5>
      </div>

      <div>
        <a href="{% url "sender:client_list" %}" class="btn btn-primary">Назад</a>
        {% if object.owner == user or user.is_superuser %}
        <a href="{% url "sender:client_update" object.pk %}" class="btn btn-primary">Редактировать</a>        
        <a href="{% url "sender:client_delete" object.pk %}" class="btn btn-outline-danger">Удалить</a>
        {% endif %}
      </div>
    </div>
    <div class="card-body">
      <h5 class="card-title">Email</h5>
      <p class="card-text">{{ object.email }}</p>

      <br />
      <h5 class="card-title">Комментарий</h5>
      <p class="card-text">{{ object.comment }}</p>

      <br />
      <h5 class="card-title">Группы рассылок</h5>

      <div class="row">
        <div class="col-4">
          <table class="table table-sm">
            <thead>
              <tr>
                <th scope="col">Рассылка</th>
                <th scope="col">Сообщение</th>
              </tr>
            </thead>
            <tbody class="table-group-divider">
              {% for obj in object.mailing_set.all %}
                <tr>
                  <td>
                    <a href="{% url "sender:mailing_detail" obj.pk %}" class="link-primary"><div>{{ obj.name }}</div></a>
                  </td>
                  <td>
                    <a href="{% url "sender:text_detail" obj.text.pk %}" class="link-primary"><div>{{ obj.text }}</div></a>
                  </td>
                </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

sender/templates/sender/mailing_detail.html
{% extends 'base.html' %}
{% load static %}

{% block header %}
  <link rel="stylesheet" href="{% static 'css/scroll_table.css' %}">  
{% endblock  %}

{% block content %}
  <h1 class="mt-5">Информация о рассылке</h1>
  <div class="card mt-4">
    <div class="card-header d-flex justify-content-between align-items-center">
      <div>
        <h5 class="card-title">{{ object.name }}</h5>
      </div>

      <div>
        {% if perms.sender.disable_mailing %}
          {% if object.status != object.STOPPED %}
          <a href="{% url "sender:disable_mailing" object.pk %}" class="btn btn-danger">Завершить</a>
          {% endif %}
        {% endif %}
        <a href="{% url "sender:mailing_list" %}" class="btn btn-primary">Назад</a>
        {% if object.owner == user or user.is_superuser %}
        <a href="{% url "sender:mailing_update" object.pk %}" class="btn btn-primary">Редактировать</a>
        <a href="{% url "sender:mailing_delete" object.pk %}" class="btn btn-outline-danger">Удалить</a>
        {% endif %}
      </div>
    </div>
    <div class="card-body">

      <form action="{% url "sender:mailing_detail" object.pk %}" id="id_form" method="post">
        {% csrf_token %}
        <table class="table table-borderless">
          <thead>
            <tr>
              <th scope="col">Сообщение</th>
              <th scope="col">Статус</th>
              <th scope="col">Периодичность</th>
              <th scope="col">Дата и время старта</th>
              <th scope="col">Дата и время окончания</th>            
            </tr>
          </thead>
          <tbody>
            <tr>
              <td><a href="{% url "sender:text_detail" object.text.pk %}">{{ object.text }}</a></td>
              {% if perms.sender.disable_mailing %}
              <td>{{ object.get_status_display }}</td>
              <td>{{ object.get_periodicity_display }}</td>
              {% else %}
              <td><select name="status" class="form-select" id="" onchange="submitForm()">
                {% for status in object.MAILING_STATUS %}
                  <option value="{{ status.0 }}" {% if object.status == status.0 %}selected{% endif %}>{{ status.1 }}</option>
                {% endfor %}
              </select></td>
              <td><select name="periodicity" class="form-select" id="" onchange="submitForm()">
                {% for periodicity in object.LAUNCH_FREQUENCY %}
                  <option value="{{ periodicity.0 }}" {% if object.periodicity == periodicity.0 %}selected{% endif %}>{{ periodicity.1 }}</option>
                {% endfor %}
              </select></td>
              {% endif %}
              <td>{{ object.start_datetime }}</td>
              <td>{% if object.end_datetime %}{{ object.end_datetime }}{% else %}-{% endif %}</td>            
            </tr>
          </tbody>
        </table>
      </form>
      

      <div class="accordion mt-4" id="accordionPanelsStayOpenExample">
        <div class="accordion-item mb-4">
          <h2 class="accordion-header">
            <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapseOne" aria-expanded="true" aria-controls="panelsStayOpen-collapseOne">
              Последние 5 записей лога
            </button>
          </h2>
          <div id="panelsStayOpen-collapseOne" class="accordion-collapse collapse show">
            <div class="accordion-body">
              <table class="table table-sm">
                <thead>
                  <tr>
                    <th>Дата и время запуска</th>
                    <th>Статус</th>
                    <th>Код ответа</th>
                    <th>Текст ответа сервера</th>
                  </tr>
                </thead>
                <tbody>
                  {% for obj in object.attempts.all|slice:":5" %}
                      <tr>
                        <td>{{ obj.started }}</td>
                        <td>{% if obj.status %}<strong class="text-success">Отправлено</strong>{% else %}<strong class="text-danger">Не отправлено</strong>{% endif %}</td>
                        <td>{{ obj.response_code }}</td>
                        <td>{{ obj.response_msg }}</td>
                      </tr>
                  {% endfor %}
                </tbody>
              </table>
              <form action="{% url "sender:attempt_clear" object.pk %}" method="post">
                {% csrf_token %}
                {% if not perms.sender.disable_mailing %}
                <button type="submit" class="btn btn-primary">Очистить попытки</button>
                {% endif %}
              </form>
            </div>
          </div>
        </div>
      </div>
      
      
      <div class="accordion mt-4" id="accordionPanelsStayOpenExample">        
        <div class="accordion-item">
          <h2 class="accordion-header">
            <button class="accordion-button collapsed" {% if perms.sender.disable_mailing %}disabled{% endif %} type="button" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapseTwo" aria-expanded="false" aria-controls="panelsStayOpen-collapseTwo">
              Клиенты: {{ object.clients.all|length }} шт.
            </button>
          </h2>
          <div id="panelsStayOpen-collapseTwo" class="accordion-collapse collapse">
            <div class="scroll-table m-3">
              <table class="table table-sm">
                <thead>
                  <tr>
                    <th>Фамилия Имя Отчество</th>
                    <th>Email</th>
                  </tr>
                </thead>
              </table>
              <div class="scroll-table-body">
                <table class="table table-sm table-hover">
                  <tbody>
                    {% for obj in object.clients.all %}
                    <tr>
                      <td><div class="d-flex position-relative">{{ obj.name }}<a href="{% url "sender:client_detail" obj.pk %}" class="stretched-link"></a></div></td>
                      <td><div class="d-flex position-relative">{{ obj.email }}<a href="{% url "sender:client_detail" obj.pk %}" class="stretched-link"></a></div></td>
                    </tr>
                    {% endfor %}
                  </tbody>
                </table>
              </div>	
            </div>
          </div>
        </div>
      </div>      
    </div>
  </div>
{% endblock %}


{% block footer %}
<script src="{% static "js/autoform.js" %}"></script>
{% endblock  %}

sender/templates/sender/mailing_list.html
{% extends 'base.html' %}

{% block content %}
  <h1 class="mt-5">Рассылки</h1>
  <p class="lead">
    Создайте рассылки по расписанию
  </p>
  {% if not perms.users.block_user and not perms.sender.disable_mailing %}
  <div class="mb-3">
    <a class="btn btn-primary" href="{% url "sender:mailing_create" %}">Создать рассылку</a>
  </div>  
  {% endif %}
  <table class="table table-hover">
    <thead>
      <tr>
        <th scope="col">Название</th>
        <th scope="col">Статус</th>
        <th scope="col">Периодичность</th>
        <th scope="col">Дата и время старта</th>
        <th scope="col">Дата и время окончания</th>     
      </tr>
    </thead>
    <tbody>
      {% for object in page_obj %}
      <tr>
        <td><div class="d-flex position-relative">{{ object.name }}<a href="{% url "sender:mailing_detail" object.pk %}" class="stretched-link"></a></div></td>
        <td class="{% if object.status == "R" %}text-success{% elif object.status == "S" %}text-secondary{% endif %}"><div class="d-flex position-relative">{{ object.get_status_display }}<a href="{% url "sender:mailing_detail" object.pk %}" class="stretched-link"></a></div></td>
        <td><div class="d-flex position-relative">{{ object.get_periodicity_display }}<a href="{% url "sender:mailing_detail" object.pk %}" class="stretched-link"></a></div></td>
        <td><div class="d-flex position-relative">{{ object.start_datetime }}<a href="{% url "sender:mailing_detail" object.pk %}" class="stretched-link"></a></div></td>
        <td><div class="d-flex position-relative">{% if object.end_datetime %}{{ object.end_datetime }}{% else %}-{% endif %}<a href="{% url "sender:mailing_detail" object.pk %}" class="stretched-link"></a></div></td>
      </tr>
      {% endfor %}
    </tbody>
  </table>

  <nav>
    <ul class="pagination">
      <li class="page-item {% if not page_obj.has_previous %}disabled{% endif %}">
        <a class="page-link" href="{% if page_obj.has_previous %}
        {% url 'sender:client_list' %}?page={{ page_obj.previous_page_number }}{% endif %}">
        Назад</a>
      </li>

      {% for page in page_obj.paginator.page_range %}
        {% if page <= page_obj.number|add:2 and page >= page_obj.number|add:-2 %}
          <li class="page-item {% if page == page_obj.number %}active{% endif %}">
            <a class="page-link" href="{% url 'sender:client_list' %}?page={{ page }}">{{ page }}</a>
          </li>
        {% endif %}
      {% endfor %}

      <li class="page-item {% if not page_obj.has_next %}disabled{% endif %}">
        <a class="page-link" href="
        {% if page_obj.has_next %}{% url 'sender:client_list' %}?page={{ page_obj.next_page_number }}{% endif %}">
        Вперед</a>
      </li>
    </ul>
  </nav>
{% endblock %}