blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page
from blog.apps import BlogConfig

from blog import views

app_name = BlogConfig.name

urlpatterns = [
    path("", cache_page(60 * 15)(views.ArticleListView.as_view()), name="list"),
    path("article/<int:pk>/", cache_page(60 * 15)(views.ArticleDetailView.as_view()), name="detail"),
    path("create/", views.ArticleCreateView.as_view(), name="create"),
    path("update/<int:pk>/", views.ArticleUpdateView.as_view(), name="update"),
    path("delete/<int:pk>/", views.ArticleDeleteView.as_view(), name="delete"),
]

config/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from config.settings import DEBUG
from debug_toolbar.toolbar import debug_toolbar_urls


urlpatterns = [
    path("ckeditor5/", include("django_ckeditor_5.urls")),
    path("admin/", admin.site.urls),
    path("", include("sender.urls", namespace="sender")),
    path("users/", include("users.urls", namespace="users")),
    path("blog/", include("blog.urls", namespace="blog")),
]

if DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += debug_toolbar_urls()

sender/urls.py
from django.urls import path

from sender import views
from sender.apps import SenderConfig

app_name = SenderConfig.name

urlpatterns = [
    path("", views.index, name="index"),

    path("clients/", views.ClientListView.as_view(), name="client_list"),
    path("clients/<int:pk>/", views.ClientDetailView.as_view(), name="client_detail"),
    path("clients/create/", views.ClientCreateView.as_view(), name="client_create"),
    path("clients/update/<int:pk>/", views.ClientUpdateView.as_view(), name="client_update"),
    path("clients/delete/<int:pk>/", views.ClientDeleteView.as_view(), name="client_delete"),

    path("texts/", views.TextListView.as_view(), name="text_list"),
    path("texts/<int:pk>/", views.TextDetailView.as_view(), name="text_detail"),
    path("texts/create/", views.TextCreateView.as_view(), name="text_create"),
    path("texts/update/<int:pk>/", views.TextUpdateView.as_view(), name="text_update"),
    path("texts/delete/<int:pk>/", views.TextDeleteView.as_view(), name="text_delete"),

    path("mailings/", views.MailingListView.as_view(), name="mailing_list"),
    path("mailings/<int:pk>/", views.MailingDetailView.as_view(), name="mailing_detail"),
    path("mailings/create/", views.MailingCreateView.as_view(), name="mailing_create"),
    path("mailings/update/<int:pk>/", views.MailingUpdateView.as_view(), name="mailing_update"),
    path("mailings/delete/<int:pk>/", views.MailingDeleteView.as_view(), name="mailing_delete"),
    path("mailings/disable/<int:pk>/", views.disable_mailing, name="disable_mailing"),

    path("attempt/clear/<int:pk>/", views.AttemptDeleteView.as_view(), name="attempt_clear"),    
]

users/urls.py
from django.urls import path

from django.contrib.auth.views import LogoutView

from users import views
from users.apps import UsersConfig

app_name = UsersConfig.name

urlpatterns = [
    path("register/", views.UserCreateView.as_view(), name="register"),
    path("confirm-email/<str:token>/", views.confirm_email, name="confirm_email"),
    path("info/", views.info_confirm_email, name="info"),
    path("login/", views.CustomLoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("profile/", views.ProfileView.as_view(), name="profile"),
    path("password-change/", views.CustomPasswordChangeView.as_view(), name="password_change"),
    path("password-change-done/", views.CustomPasswordChangeDoneView.as_view(), name="password_change_done"),
    path("password-reset/", views.CustomPasswordResetView.as_view(), name="password_reset"),
    path("password-reset-done/", views.CustomPasswordResetDoneView.as_view(), name="password_reset_done"),
    path("password-reset-confirm/<uidb64>/<token>/", views.CustomPasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    path("password-reset-complete/", views.CustomPasswordResetCompleteView.as_view(), name="password_reset_complete"),
    path("list/", views.UserListView.as_view(), name="user_list"),
    path("change-user-activity/<int:pk>", views.change_user_activity, name="change_user_activity"),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

NULLABLE = {"blank": True, "null": True}


class User(AbstractUser):
    username = None
    email = models.EmailField(verbose_name="Почта", unique=True)
    token = models.CharField(max_length=16, **NULLABLE)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = "пользователя"
        verbose_name_plural = "пользователи"
        ordering = ("-pk",)
        permissions = {
            ("block_user", "Может блокировать пользователя"),
        }

users/forms.py
from django.contrib.auth.forms import (
    AuthenticationForm,
    UserChangeForm,
    UserCreationForm,
    PasswordChangeForm,
    PasswordResetForm,
    SetPasswordForm,
)
from django import forms


from users.models import User


class FormStyleMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field in self.fields.values():
            field.widget.attrs.update({"class": "form-control"})


class CustomUserCreationForm(FormStyleMixin, UserCreationForm):
    """Форма регистрации"""

    class Meta:
        model = User
        fields = (
            "email",
            "password1",
            "password2",
        )


class CustomAuthenticationForm(FormStyleMixin, AuthenticationForm):
    """Форма авторизации"""


class CustomUserChangeForm(FormStyleMixin, UserChangeForm):
    """Форма профиля пользователя"""

    password = forms.CharField(widget=forms.HiddenInput(), required=False)

    class Meta:
        model = User
        fields = (
            "email",
            "first_name",
            "last_name",
        )


class CustomPasswordChangeForm(FormStyleMixin, PasswordChangeForm):
    """Форма смены пароля"""


class CustomPasswordResetForm(FormStyleMixin, PasswordResetForm):
    """Форма сброса пароля"""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["email"].widget.attrs.update(
            {"placeholder": "Укажите email, указанный при регистрации"}
        )


class CustomSetPasswordForm(FormStyleMixin, SetPasswordForm):
    """Форма установки пароля после сброса"""

users/views.py
from secrets import token_hex
from django.contrib.auth.decorators import permission_required
from django.contrib.auth.mixins import (
    LoginRequiredMixin,
    UserPassesTestMixin,
)
from django.core.exceptions import PermissionDenied
from django.core.mail import EmailMessage
from django.db import transaction
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy, reverse
from django.contrib.auth.views import (
    LoginView,
    PasswordChangeView,
    PasswordChangeDoneView,
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
)
from django.views.generic import ListView, UpdateView, CreateView

from sender.models import Mailing
from users.forms import (
    CustomAuthenticationForm,
    CustomPasswordChangeForm,
    CustomPasswordResetForm,
    CustomSetPasswordForm,
    CustomUserChangeForm,
    CustomUserCreationForm,
)
from users.models import User


class UserCreateView(CreateView):
    """Регистрация"""

    model = User
    form_class = CustomUserCreationForm
    template_name = "users/auth.html"
    success_url = reverse_lazy("users:info")
    extra_context = {
        "title": "Регистрация",
        "button": "Регистрация",
    }

    def form_valid(self, form):
        """Генерация токена и отправка подтверждения email"""
        if form.is_valid:
            user = form.save()
            token = token_hex(8)
            user.is_active = False
            user.token = token

            host = self.request.get_host()
            tail = reverse("users:confirm_email", args=[token])
            email_body = f"Перейдите по ссылке, чтобы подтвердить регистрацию: http://{host}{tail}"

            email = EmailMessage(
                subject="Подтверждение регистрации",
                body=email_body,
                to=[
                    user.email,
                ],
            )
            email.send(fail_silently=False)

        return super().form_valid(form)


def confirm_email(request, token):
    user = get_object_or_404(User, token=token)
    user.is_active = True
    user.token = None
    user.save(update_fields=["is_active", "token"])
    return redirect(reverse("users:login"))


def info_confirm_email(request):
    context = {
        "title": "Подтверждение регистрации",
        "text": "На Ваш email отправлена ссылка для подтверждения регистрации",
    }
    return render(request, "users/info.html", context)


class CustomLoginView(LoginView):
    """Авторизация"""

    form_class = CustomAuthenticationForm
    template_name = "users/auth.html"
    extra_context = {
        "title": "Авторизация",
        "button": "Вход",
        "forget_pass": True,
    }


class ProfileView(LoginRequiredMixin, UpdateView):
    """Профиль пользователя"""

    form_class = CustomUserChangeForm
    template_name = "users/auth.html"
    success_url = reverse_lazy("users:profile")
    extra_context = {
        "title": "Профиль",
        "button": "Сохранить",
        "change_pass": "Сменить пароль",
    }

    def get_object(self):
        return self.request.user


class CustomPasswordChangeView(LoginRequiredMixin, PasswordChangeView):
    """Смена пароля"""

    form_class = CustomPasswordChangeForm
    success_url = reverse_lazy("users:password_change_done")
    template_name = "users/auth.html"
    extra_context = {
        "button": "Сменить пароль",
    }


class CustomPasswordChangeDoneView(LoginRequiredMixin, PasswordChangeDoneView):
    """Успешное изменение пароля"""

    template_name = "users/info.html"
    extra_context = {
        "text": "Пароль успешно установлен",
    }


class CustomPasswordResetView(PasswordResetView):
    """Сброс пароля забываки"""

    form_class = CustomPasswordResetForm
    template_name = "users/auth.html"
    email_template_name = "users/password_reset_email.html"
    success_url = reverse_lazy("users:password_reset_done")
    extra_context = {
        "button": "Отправить",
    }


class CustomPasswordResetDoneView(PasswordResetDoneView):
    """Сообщение с инструкцией сброса пароля"""

    template_name = "users/info.html"


class CustomPasswordResetConfirmView(PasswordResetConfirmView):
    """Установка пароля после сброса"""

    form_class = CustomSetPasswordForm
    template_name = "users/auth.html"
    success_url = reverse_lazy("users:password_reset_complete")
    extra_context = {
        "button": "Отправить",
    }


class CustomPasswordResetCompleteView(PasswordResetCompleteView):
    """Сообщение об успешном восстановлении пароля"""

    template_name = "users/info.html"
    extra_context = {
        "text": "Пароль успешно восстановлен, теперь можете войти",
        "link": {
            "caption": "Войти",
            "link": reverse_lazy("users:login"),
        },
    }


class UserListView(UserPassesTestMixin, ListView):
    """Список пользователей сервиса. Виден только модератору и админу"""

    paginate_by = 50

    def test_func(self):
        user = self.request.user
        return user.has_perm("users.view_user") or user.is_superuser

    def get_queryset(self):
        queryset = User.objects.all()
        if self.request.user.is_superuser:
            return queryset
        return queryset.filter(is_superuser=False)


@permission_required("users.block_user", PermissionDenied)
def change_user_activity(request, pk):
    """
    Изменение статуса пользователя.
    Во время блокировки останавливаются все его рассылки
    """

    user = User.objects.get(pk=pk)

    # Админа и персонал деактивировать нельзя (только из админки)
    if user.is_superuser or user.is_staff:
        raise PermissionDenied

    if user.is_active:
        # Блокировка
        user.is_active = False

        # Остановка всех рассылок
        update_list = []
        for mailing in user.mailings.exclude(status=Mailing.STOPPED):
            mailing.status = mailing.STOPPED
            update_list.append(mailing)
        # Сохранение всех объектов одной транзакцией
        with transaction.atomic():
            for record in update_list:
                record.save(update_fields=["status"])
    else:
        # Активация
        user.is_active = True
    user.save(update_fields=("is_active",))

    return redirect(reverse_lazy("users:user_list"))

users/templates/users/auth.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  <div class="row">
    <div class="col-4"></div>
    <div class="col-4">
      <div class="card">
        <form action="" method="post">
          <div class="card-header text-center"><h3>{{ title }}</h3></div>
          <div class="card-body">            
            {% csrf_token %}
            {{ form.as_p }}            
            <button type="submit" class="btn btn-primary form-control">{{ button }}</button>
            {% if change_pass %}
            <a class="btn btn-secondary form-control mt-3" href="{% url "users:password_change" %}">{{ change_pass }}</a>
            {% endif %}
          </div>
          {% if forget_pass %}
          <div class="card-footer">
            <a href="{% url "users:password_reset" %}">Забыли пароль?</a>
          </div>
          {% endif %}
        </form>
      </div>
    </div>
  </div>
{% endblock %}

users/templates/users/info.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  <div class="row mt-4">
    <div class="col-3"></div>
    <div class="col-6">
      <div class="text-center mt-4">
        <h3>{{ title }}</h3>
        <p>{{ text }}</p>
        {% if link %}
        <p><a href="{{ link.link }}">{{ link.caption }}</a></p>
        {% endif %}        
      </div>
    </div>
  </div>
{% endblock %}

users/templates/users/password_reset_email.html
{% load i18n %}{% autoescape off %}
{% blocktranslate %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktranslate %}

{% translate "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% translate 'Your username, in case you’ve forgotten:' %} {{ user.get_username }}

{% translate "Thanks for using our site!" %}

{% blocktranslate %}The {{ site_name }} team{% endblocktranslate %}

{% endautoescape %}

users/templates/users/user_list.html
{% extends 'base.html' %}

{% block content %}
  <h1 class="mt-5">Пользователи сервиса</h1>

  <div class="mb-4 mt-4">
    <div class="row">
      <div class="col-12 col-sm-1 col-md-1 col-lg-1 col-xl-1 col-xxl-1"></div>
      <div class="col-12 col-sm-3 col-md-3 col-lg-3 col-xl-4 col-xxl-4"><strong>Полное имя</strong></div>
      <div class="col-12 col-sm-3 col-md-3 col-lg-3 col-xl-3 col-xxl-3"><strong>Email</strong></div>
      <div class="col-12 col-sm-3 col-md-3 col-lg-3 col-xl-3 col-xxl-2"><strong>Последнее посещени</strong></div>
      <div class="col-12 col-sm-2 col-md-1 col-lg-1 col-xl-1 col-xxl-1"></div>
    </div>
    <hr>
    {% for object in page_obj %}    
    <div class="row {% if not object.is_active %}text-danger{% endif %}">
      <div class="col-12 col-sm-1 col-md-1 col-lg-1 col-xl-1 col-xxl-1 text-end">{% if not object.is_active %}(BAN){% endif %}</div>        
      <div class="col-12 col-sm-3 col-md-3 col-lg-3 col-xl-4 col-xxl-4">{{ object.get_full_name }}</div>
      <div class="col-12 col-sm-3 col-md-3 col-lg-3 col-xl-3 col-xxl-3">{{ object.email }}</div>
      <div class="col-12 col-sm-3 col-md-3 col-lg-3 col-xl-3 col-xxl-2">{{ object.last_login }}</div>
      <div class="col-12 col-sm-2 col-md-1 col-lg-1 col-xl-1 col-xxl-1">
        {% if object.is_active %}
          <a class="btn btn-danger {% if object.is_superuser or object.is_staff %}btn-secondary disabled{% endif %}" style="--bs-btn-padding-y: 2px; --bs-btn-padding-x: 5px; --bs-btn-font-size: 12px; min-width: 110px;" href="{% url "users:change_user_activity" object.pk %}">Заблокировать</a>
        {% else %}
          <a class="btn btn-success" style="--bs-btn-padding-y: 2px; --bs-btn-padding-x: 5px; --bs-btn-font-size: 12px; min-width: 110px;" href="{% url "users:change_user_activity" object.pk %}">Разблокировать</a>
        {% endif %}        
      </div>
    </div>
    {% endfor %}
  </div>


  <nav>
    <ul class="pagination">
      <li class="page-item {% if not page_obj.has_previous %}disabled{% endif %}">
        <a class="page-link" href="{% if page_obj.has_previous %}
        {% url 'sender:client_list' %}?page={{ page_obj.previous_page_number }}{% endif %}">
        Назад</a>
      </li>

      {% for page in page_obj.paginator.page_range %}
        {% if page <= page_obj.number|add:2 and page >= page_obj.number|add:-2 %}
          <li class="page-item {% if page == page_obj.number %}active{% endif %}">
            <a class="page-link" href="{% url 'sender:client_list' %}?page={{ page }}">{{ page }}</a>
          </li>
        {% endif %}
      {% endfor %}

      <li class="page-item {% if not page_obj.has_next %}disabled{% endif %}">
        <a class="page-link" href="
        {% if page_obj.has_next %}{% url 'sender:client_list' %}?page={{ page_obj.next_page_number }}{% endif %}">
        Вперед</a>
      </li>
    </ul>
  </nav>
{% endblock %}